```sql
CREATE TABLE Dashboard (
  MESSAGE_TIMESTAMP TEXT PRIMARY KEY,
  CASE_NUMBER TEXT,
  SALESFORCE_ASSET TEXT,
  REP_NAME TEXT,
  HELPER_NAME TEXT,
  STATUS TEXT,
  URL TEXT,
  BYPASS_SALESFORCE TEXT,
  LOCKED_UNIX_TIMESTAMP INTEGER,
  LAST_UPDATED TEXT,
  SUPPORT_MESSAGE_TEXT TEXT,
  RELAY_MESSAGE_TEXT TEXT,
  CASE_RECORD_ID TEXT
);

CREATE TABLE Error (
  ERROR_TIMESTAMP_UTC TEXT PRIMARY KEY,
  ERROR_WORKER_NAME TEXT,
  ERROR_MESSAGE TEXT,
  ERROR_TYPE TEXT
);

CREATE TABLE Help (
  HELP_ITEM TEXT PRIMARY KEY,
  HELP_MAIN_CATEGORY TEXT,
  HELP_SUB_CATEGORY TEXT,
  HELP_DESCRIPTION TEXT,
  HELP_SUB_CATEGORY_ORDER TEXT,
  LAST_UPDATED TEXT
);

CREATE TABLE Settings (
  DB_SETTING_NAME TEXT PRIMARY KEY,
  SETTING_LABEL TEXT,
  SETTING_VALUE TEXT,
  PAGE_NAME TEXT,
  SETTING_DESCRIPTION TEXT,
  CATEGORY_NAME TEXT,
  INPUT_TYPE TEXT,
  OPTIONS TEXT,
  OPTIONS_SOURCE TEXT,
  LAST_UPDATED TEXT
);

CREATE TABLE User (
  SLACK_USER_ID TEXT PRIMARY KEY,
  SF_USER_ID TEXT,
  FIRST_LAST TEXT,
  USERNAME TEXT,
  PASSWORD TEXT,
  USER_ROLE TEXT,
  LAST_UPDATED TEXT,
  FAILED_LOGIN_ATTEMPTS TEXT,
  SYNC_DUE_AT_TIMESTAMP TEXT,
  SESSION_TOKEN TEXT,
  LOGIN_TOKEN TEXT,
  LOGIN_TOKEN_EXPIRES TEXT,
  STATE TEXT,
  NONCE TEXT,
  CODE_VERIFIER TEXT,
  GUEST_SESSION_EXPIRES TEXT,
  GOOGLE_SUB TEXT
);
